# default details for Logica's SMSC simulator
smpp:
    host: '127.0.0.1'
    port: 6000
    username: 'hugo'
    password: 'ggoohu'

# RabbitMQ default login details
amqp:
    host: localhost
    port: 5672
    username: guest
    password: guest
    vhost: /
    exchange: exchange
    outbound: smpp.outbound
    outbound_key: outbound.key
    inbound_key: inbound.key
    delivery_report_key: inbound.delivery_report
    accepted_key: inbound.accepted
    rejected_key: inbound.rejected
    
